services:
  examen-bdd:
    image: postgres:12
    environment:
      POSTGRES_USER: examen-bdd
      POSTGRES_PASSWORD: examen-bdd
      POSTGRES_DB: examen-bdd
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

      