services:
  progen-db:
    image: postgres:12
    environment:
      POSTGRES_USER: github-setup
      POSTGRES_PASSWORD: github-setup
      POSTGRES_DB: github-setup
    ports:
      - "5432:5432"
    volumes:
      - ./Db/init.sql:/docker-entrypoint-initdb.d/init.sql

      