export type GithubProfile = {
    login: string ,     //'LaCapitainerie',
    id: string ,    //66835496,
    node_id: string ,   //'MDQ6VXNlcjY2ODM1NDk2',
    avatar_url: string ,    //'https://avatars.githubusercontent.com/u/66835496?v=4',
    gravatar_id: string ,   //'',
    url: string ,   //'https://api.github.com/users/LaCapitainerie',
    html_url: string ,  //'https://github.com/LaCapitainerie',
    followers_url: string ,     //'https://api.github.com/users/LaCapitainerie/followers',
    following_url: string ,     //'https://api.github.com/users/LaCapitainerie/following{/other_user}',
    gists_url: string ,     //'https://api.github.com/users/LaCapitainerie/gists{/gist_id}',
    starred_url: string ,   //'https://api.github.com/users/LaCapitainerie/starred{/owner}{/repo}',
    subscriptions_url: string ,     //'https://api.github.com/users/LaCapitainerie/subscriptions',
    organizations_url: string ,     //'https://api.github.com/users/LaCapitainerie/orgs',
    repos_url: string ,     //'https://api.github.com/users/LaCapitainerie/repos',
    events_url: string ,    //'https://api.github.com/users/LaCapitainerie/events{/privacy}',
    received_events_url: string ,   //'https://api.github.com/users/LaCapitainerie/received_events',
    type: string ,  //'User',
    user_view_type: string ,    //'private',
    site_admin: string ,    //false,
    name: string ,  //'Hugo',
    company: string ,   //'CNPP',
    blog: string ,  //'https://gilbot.fr',
    location: string ,  //'France',
    email: string ,     //'hugo.antreassian@gmail.com',
    hireable: string ,  //null,
    bio: string ,   //'Master in Logic Gates and Boolean Algebra',
    twitter_username: string ,  //null,
    notification_email: string ,    //null,
    public_repos: string ,  //23,
    public_gists: string ,  //0,
    followers: string ,     //1,
    following: string ,     //1,
    created_at: string ,    //'2020-06-12T14:09:23Z',
    updated_at: string ,    //'2024-12-21T13:01:05Z',
    private_gists: string ,     //0,
    total_private_repos: string ,   //14,
    owned_private_repos: string ,   //14,
    disk_usage: string ,    //64511,
    collaborators: string ,     //0,
    two_factor_authentication: string ,     //true,
    plan: {//{
      name: string ,    //'pro',
      space: string ,   //976562499,
      collaborators: string ,   //0,
      private_repos: string ,   //9999
    }
  }